### ISSUE TITLE
Revamp logic for run.pl to support regression manager

### ISSUE THREAD

**Issue by dhruvbehl** [SimpleCPU/SimpleCPU#27]
There is a need to change the logic in run.pl file for the execution of the test-cases to support regression manager where test file path needs to be handled properly.

**Comment by raulbehl** [comment]
I have added a "-regress" option to the run.pl script. 
Since the regression manager script calls the perl script with the complete path to the hex files of the test, it should invoke the perl script with the -regress flag set. This would avoid the deletion of the test-cases from the test directory. 
Fix in 2ddea43

**Comment by raulbehl** [comment]
I have fixed the regressionManager.py script as well.

Fix in 418c6e2
